---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mmrmod

<!-- badges: start -->
<!-- badges: end -->

The function \code{mmrmod} provides inference results for the mixed models for 
repeated measures (MMRM) analysis without assuming orthogonality property 
between fixed effect and variance-covariance parameters.
For the orthogonality issue, refer to  
[Maruo et al. (2020)](https://doi.org/10.1002/sim.8474).

## Installation

You can install the development version of mmrmod from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("kzkzmr/mmrmod")
```

## Example
```{r example}
library(mmrmod)
library(mmrm)
# fev_data from mmrm package
data(fev_data)

res <- mmrmod(data = fev_data, outcome = FEV1, group = ARMCD, time = AVISIT,
              subject = USUBJID, covariate = c("RACE", "SEX", "FEV1_BL"),
              covfactor = c(1, 1, 0))
res$marg.mean
res$diff.mean
```
